-- =============================================
-- TEST SCHEMA — creates stripped-down tables for unit tests in H2 Oracle mode
-- =============================================

CREATE TABLE IF NOT EXISTS CARD (
    CARDNUMBER    VARCHAR2(20)  NOT NULL,
    MAINCARDNO    VARCHAR2(20),
    CARDTYPE      VARCHAR2(20),
    CARDPRODUCT   VARCHAR2(20),
    CARDSTATUS    VARCHAR2(20),
    MGRFLAG       NUMBER        NOT NULL,
    LASTUPDATEDTIME TIMESTAMP   NOT NULL,
    CREATEDTIME   TIMESTAMP     NOT NULL,
    APPLICATIONID VARCHAR2(12),
    CONSTRAINT PK_CARD PRIMARY KEY (CARDNUMBER)
);

CREATE TABLE IF NOT EXISTS RECARDREQUEST (
    REQUESTID       VARCHAR2(38)  NOT NULL,
    PRIORITYLEVEL   VARCHAR2(20),
    REASON          VARCHAR2(255),
    REMARKS         VARCHAR2(276),
    STATUS          VARCHAR2(16),
    REQUESTEDUSER   VARCHAR2(32),
    APPROVEDUSER    VARCHAR2(32),
    LASTUPDATEDUSER VARCHAR2(20)  NOT NULL,
    CREATEDTIME     TIMESTAMP,
    LASTUPDATEDTIME TIMESTAMP     NOT NULL,
    REJECTREMARK    VARCHAR2(255),
    ISMIGRATED      VARCHAR2(20),
    RENEWCONFIRMATION VARCHAR2(3),
    REQUESTREASONCODE VARCHAR2(6),
    CALLLOGID       VARCHAR2(12),
    MAINCARDNUMBER  VARCHAR2(20),
    REQUESTEDCARD   VARCHAR2(20),
    ASSOCIATEDCARD  VARCHAR2(20),
    CUSTOMERID      VARCHAR2(20),
    ACCOUNTNUMBER   VARCHAR2(15),
    APPLICATIONID   VARCHAR2(15),
    CARDCATEGORY    VARCHAR2(10),
    ISPRIMARY       VARCHAR2(10)  NOT NULL,
    BULKID          VARCHAR2(60),
    ASSIGNUSER      VARCHAR2(32),
    CONSTRAINT PK_RECARDREQUEST PRIMARY KEY (REQUESTID)
);

CREATE TABLE IF NOT EXISTS MD_ENGINE_CONFIGURATIONS (
    ENGINEID              VARCHAR2(20)  NOT NULL,
    ENGINESTATUS          NUMBER(1)     NOT NULL,
    LASTEXECUTIONTIME     TIMESTAMP,
    NEXTSCHEDULEDRUNTIME  TIMESTAMP,
    CARDSPROCESSEDPERRUN  NUMBER,
    AVGPROCESSINGTIMEPERCARD NUMBER,
    THREADSRUNPARALLEL    NUMBER,
    BATCHSIZE             NUMBER,
    PERIOD                VARCHAR2(20),
    LASTUPDATEDTIME       TIMESTAMP     NOT NULL,
    CONSTRAINT PK_MD_ENGINE_CONFIGURATIONS PRIMARY KEY (ENGINEID)
);

CREATE TABLE IF NOT EXISTS MD_ENGINE_EXECUTION_LOG (
    RUNID           VARCHAR2(20)  NOT NULL,
    STARTTIME       TIMESTAMP     NOT NULL,
    ENDTIME         TIMESTAMP,
    STATUS          VARCHAR2(16)  NOT NULL,
    CARDSPROCESSED  NUMBER,
    AVGTIMEPERCARD  NUMBER,
    THREADCOUNT     NUMBER,
    BATCHSIZE       NUMBER,
    ERRORCOUNT      NUMBER DEFAULT 0,
    ERRORMESSAGE    VARCHAR2(500),
    CONSTRAINT PK_MD_ENGINE_EXECUTION_LOG PRIMARY KEY (RUNID)
);
