-- ==========================================
-- SCHEMA CREATION SCRIPT FOR RECARDING MONITORING DASHBOARD
-- ==========================================

/*
-- UNCOMMENT TO RESET THE SCHEMA (DROP TABLES)
DROP TABLE MD_ENGINE_CONFIGURATIONS;
-- DROP TABLE RECARDREQUEST;
-- DROP TABLE CARD;
*/

-- NOTE: The CARD and RECARDREQUEST tables are assumed to exist in the production environment.
-- For local/test environments, you can uncomment the definitions below to create them.

/*
-- UNCOMMENT TO CREATE CARD TEST TABLE
CREATE TABLE CARD (
    CARDNUMBER VARCHAR2(20) NOT NULL,
    MAINCARDNO VARCHAR2(20),
    CARDTYPE VARCHAR2(20),
    CARDPRODUCT VARCHAR2(20),
    CARDSTATUS VARCHAR2(20),
    MGRFLAG NUMBER NOT NULL,
    LASTUPDATEDTIME DATE NOT NULL,
    CREATEDTIME DATE NOT NULL,
    APPLICATIONID VARCHAR2(12),
    CONSTRAINT PK_CARD PRIMARY KEY (CARDNUMBER)
);

-- UNCOMMENT TO CREATE RECARDREQUEST TEST TABLE
CREATE TABLE RECARDREQUEST (
    REQUESTID VARCHAR2(38) NOT NULL,
    PRIORITYLEVEL VARCHAR2(20),
    REASON VARCHAR2(255),
    REMARKS VARCHAR2(276),
    STATUS VARCHAR2(16),
    REQUESTEDUSER VARCHAR2(32),
    APPROVEDUSER VARCHAR2(32),
    LASTUPDATEDUSER VARCHAR2(20) NOT NULL,
    CREATEDTIME DATE,
    LASTUPDATEDTIME DATE NOT NULL,
    REJECTREMARK VARCHAR2(255),
    ISMIGRATED VARCHAR2(20),
    RENEWCONFIRMATION VARCHAR2(3),
    REQUESTREASONCODE VARCHAR2(6),
    CALLLOGID VARCHAR2(12),
    MAINCARDNUMBER VARCHAR2(20),
    REQUESTEDCARD VARCHAR2(20),
    ASSOCIATEDCARD VARCHAR2(20),
    CUSTOMERID VARCHAR2(20),
    ACCOUNTNUMBER VARCHAR2(15),
    APPLICATIONID VARCHAR2(15),
    CARDCATEGORY VARCHAR2(10),
    ISPRIMARY VARCHAR2(10) NOT NULL,
    BULKID VARCHAR2(60),
    ASSIGNUSER VARCHAR2(32),
    CONSTRAINT PK_RECARDREQUEST PRIMARY KEY (REQUESTID)
);

-- UNCOMMENT TO CREATE INDEXES ON CARD AND RECARDREQUEST
CREATE INDEX IDX_CARD_MGRFLAG ON CARD(MGRFLAG);
CREATE INDEX IDX_CARD_CARDPRODUCT ON CARD(CARDPRODUCT);
CREATE INDEX IDX_CARD_LASTUPDATEDTIME ON CARD(LASTUPDATEDTIME);
CREATE INDEX IDX_RECARDREQ_REQCARD ON RECARDREQUEST(REQUESTEDCARD);
CREATE INDEX IDX_RECARDREQ_REASON ON RECARDREQUEST(REASON);
*/

-- ==========================================
-- NEW TABLES FOR ENGINE TELEMETRY & EXECUTION HISTORY
-- ==========================================

-- Table to hold current configurations/state for each engine
CREATE TABLE MD_ENGINE_CONFIGURATIONS (
    ENGINEID VARCHAR2(20) NOT NULL,
    ENGINESTATUS NUMBER(1) NOT NULL, -- 1 = Running, 0 = Stopped
    LASTEXECUTIONTIME DATE,
    NEXTSCHEDULEDRUNTIME DATE,
    CARDSPROCESSEDPERRUN NUMBER,
    AVGPROCESSINGTIMEPERCARD NUMBER, -- Average seconds per card (e.g. 0.85)
    THREADSRUNPARALLEL NUMBER,
    BATCHSIZE NUMBER,
    PERIOD VARCHAR2(20), -- e.g. "10:30-10:45"
    LASTUPDATEDTIME DATE NOT NULL,
    CONSTRAINT PK_MD_ENGINE_CONFIGURATIONS PRIMARY KEY (ENGINEID)
);

-- ==========================================
-- END OF SCHEMA
-- ==========================================
